name: Deploy to Self-Hosted Server

on:
  push:
    branches:
      - main # Change to your default branch if necessary

jobs:
  build:
    runs-on: self-hosted # Specify that this job should run on a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t aeon . # Replace with your desired image name

      - name: Run Docker Container
        run: |
          # Stop and remove existing container if running
          docker stop aeon-test || true
          docker rm aeon-test || true

          # Run the Docker container on port 3001
          docker run -d --name aeon-test -p 3001:3000 aeon # Adjust internal port if necessary
